["Ahri"] = {
     [6.5] = {
        ["skin"] = "Coven",
        ["tier"] = 4,
        ["render"] = "Ahri Coven TFT Render.png",
        ["origin"] = {"Syndicate"},
        ["class"] = {"Arcanist"},
        ["abilityname"] = "Orb of Deception",
        ["abilityicon"] = "Orb of Deception.png",
        ["active"] = "Fires an orb in a line for 5 hexes, dealing {{ap|140|210|500}} {{tiptft|AP|{{as|AP}}}} {{as|magic damage}} to all enemies it passes through on the way out and the way back. She fires {{ap|1|1|2}} additional orbs for each time she casts in combat, enemies take 60% damage for each subsequent orb. The orbs are fired to form a circular arc with 10° between each orb.",
        ["hp"] = 800,
        ["mana"] = 50,
        ["startmana"] = 30,
        ["ad"] = 45,
        ["as"] = 0.8,
        ["range"] = 4,
        ["arm"] = 30,
        ["mr"] = 30,
        ["behavior"] = "Ranged"
      },
},
["Alistar"] = {
    [6.5] = {
        ["skin"] = "Hextech",
        ["tier"] = 4,
        ["render"] = "Alistar Hextech TFT Render.png",
        ["origin"] = {"Hextech"},
        ["class"] = {"Colossus"},
        ["abilityname"] = "Pulverize",
        ["abilityicon"] = "Pulverize.png",
        ["active"] = "Charges at his target, {{tip|TFT airborne|knocking}} them back for a short distance. Then he slams the ground, dealing {{ap|200|325|1200}} {{tiptft|AP|{{as|AP}}}} {{as|magic damage}} and {{tip|TFT stun|stunning}} all nearby enemies for {{ap|1.5|2|8}} seconds.",
        ["hp"] = 1400,
        ["mana"] = 160,
        ["startmana"] = 80,
        ["ad"] = 90,
        ["as"] = 0.6,
        ["range"] = 1,
        ["arm"] = 80,
        ["mr"] = 80,
        ["behavior"] = "Melee"
      },
},
["Blitzcrank"] = {
       [6.5] = {
        ["skin"] = "Original",
        ["variant"] = "old",
        ["tier"] = 2,
        ["render"] = "Blitzcrank TFT Render old.png",
        ["origin"] = {"Scrap"},
        ["class"] = {"Bodyguard"},
        ["abilityname"] = "Rocket Grab",
        ["abilityicon"] = "Rocket Grab.png",
        ["active"] = "{{tip|TFT airborne|Pulls}} the farthest enemy into melee range, dealing {{ap|150|300|900}} {{tiptft|AP|{{as|AP}}}} {{as|magic damage}} and {{tip|TFT stun|stunning}} them for {{fd|1.5}} seconds. Additionally his next basic attack {{tip|TFT airborne|knocks up}} his target for 1 second. Allies within range will prioritize attacking that enemy.",
        ["hp"] = 650,
        ["mana"] = 175,
        ["startmana"] = 175,
        ["ad"] = 65,
        ["as"] = 0.5,
        ["range"] = 1,
        ["arm"] = 45,
        ["mr"] = 45,
        ["behavior"] = "Melee"
      },
}